#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."
release_version="${1:-v4.0.0}"
if [[ ! "$release_version" =~ ^v[0-9]+\.[0-9]+\.[0-9]+(-[A-Za-z0-9.-]+)?$ ]]; then
    echo 'Expected a release tag such as v4.0.0.' >&2
    exit 1
fi
php -r 'require "modules/gateways/btcpay/version.php"; exit($argv[1] === "v" . BTCPAY_WHMCS_VERSION ? 0 : 1);' "$release_version"
composer validate --strict
composer install --no-dev --prefer-dist --no-interaction --no-progress --optimize-autoloader
composer check-platform-reqs --no-dev

mkdir -p dist
release_stage="$(mktemp -d)"
# The staging directory is generated by this script and contains only copies.
trap 'rm -r -- "$release_stage"' EXIT
cp -R modules "$release_stage/modules"
cp -R includes "$release_stage/includes"
# Overwrite upgrades can leave these in a developer checkout. Never distribute them.
rm -f -- "$release_stage/modules/gateways/btcpay/bp_lib.php" "$release_stage/modules/gateways/btcpay/bp_options.php"
cp LICENSE GUIDE.md README.md "$release_stage/"
release_archive="$PWD/dist/BTCPay-WHMCS-Plugin-$release_version.zip"
if [[ -e "$release_archive" ]]; then
    echo "Archive already exists: $release_archive. Move it aside before building again." >&2
    exit 1
fi
(cd "$release_stage" && zip -qr "$release_archive" modules includes LICENSE GUIDE.md README.md)
php tests/release_artifact_test.php "$release_archive"
echo "Built $release_archive"
